# This is a basic workflow to help you get started with Actions

name: Travellings-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "23 3 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      issues: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Test action
        uses: Jiaocz/travellings-link-checker@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          member-list: "https://raw.githubusercontent.com/travellings-link/travellings/master/member.md"
          labels: "invalid"
